<a href="https://colab.research.google.com/github/aaaa831108/dl-test/blob/main/class01/class01__%E4%B8%8A%E8%AA%B2ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Basics

In [1]:
import torch
import numpy as np

In [2]:
tensor = torch.rand(2,3)
matrix = np.random.rand(2,3)
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[0.2134, 0.7716, 0.4598],
        [0.8600, 0.7039, 0.3989]])
Matrix:
 [[0.46766501 0.82519703 0.86475925]
 [0.47253214 0.66658831 0.70101085]]


In [3]:
tensor = torch.zeros(2,3)
matrix = np.zeros((2,3))
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
tensor = torch.ones(2,3)
matrix = np.ones((2,3))
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
print(f"Tensor:\n {tensor.dtype}")
print(f"Matrix:\n {matrix.dtype}")

Tensor:
 torch.float32
Matrix:
 float64


In [11]:
print(f"Tensor:\n {tensor.size()}")
print(f"Tensor:\n {tensor.shape}")
print(f"Matrix:\n {matrix.shape}")

Tensor:
 torch.Size([2, 3])
Tensor:
 torch.Size([2, 3])
Matrix:
 (2, 3)


In [15]:
# list to torch
tensor = torch.tensor([2.3, 1.2, 5.7])
print(f"Tensor:\n {tensor.size()}")

# list to numpy
matrix = np.array([2.3, 1.2, 5.7])
print(f"Matrix:\n {matrix.shape}")

Tensor:
 torch.Size([3])
Matrix:
 (3,)


In [16]:
# numpy <=> torch
tensor = torch.tensor([1, 2, 3])
matrix = np.array([1, 2, 3])
print(torch.from_numpy(matrix))
print(tensor.numpy())

tensor([1, 2, 3])
[1 2 3]


In [17]:
# call by reference
tensor = torch.tensor([1, 2, 3])
matrix = tensor.numpy()

tensor += 1
print(tensor)
print(matrix)

tensor([2, 3, 4])
[2 3 4]


In [18]:
# operator 
t1 = torch.tensor([2.3, 1.2, 5.7])
t2 = torch.tensor([3.2, 2.8, 7.8])
print(torch.add(t1, t2)) # t1 + t2
print(torch.add(t1, t2)) # t1 - t2
print(torch.mul(t1, t2)) # t1 * t2
print(torch.div(t1, t2)) # t1 / t2

tensor([ 5.5000,  4.0000, 13.5000])
tensor([ 5.5000,  4.0000, 13.5000])
tensor([ 7.3600,  3.3600, 44.4600])
tensor([0.7188, 0.4286, 0.7308])


In [19]:
# slice
tensor = torch.rand(5,3)
print(tensor)
print(tensor[:,1:3])
print(tensor[1,1].item())

tensor([[0.0904, 0.1989, 0.4505],
        [0.5080, 0.7239, 0.4966],
        [0.8924, 0.2519, 0.2047],
        [0.2394, 0.6856, 0.8537],
        [0.6466, 0.0044, 0.9072]])
tensor([[0.1989, 0.4505],
        [0.7239, 0.4966],
        [0.2519, 0.2047],
        [0.6856, 0.8537],
        [0.0044, 0.9072]])
0.7239065766334534


In [24]:
tensor[1,1].item?

Object `item` not found.


In [ ]:
# view
tensor = torch.rand(2,6)
print(tensor)
print(tensor.view(3,4))
print(tensor.view(12))
print(tensor.view(12,1))
print(tensor.view(1,12))
print(tensor.view(-1,3))

tensor([[0.9594, 0.3548, 0.9751, 0.5854, 0.6431, 0.8459],
        [0.8374, 0.4420, 0.2574, 0.1708, 0.4292, 0.1682]])
tensor([[0.9594, 0.3548, 0.9751, 0.5854],
        [0.6431, 0.8459, 0.8374, 0.4420],
        [0.2574, 0.1708, 0.4292, 0.1682]])
tensor([0.9594, 0.3548, 0.9751, 0.5854, 0.6431, 0.8459, 0.8374, 0.4420, 0.2574,
        0.1708, 0.4292, 0.1682])
tensor([[0.9594],
        [0.3548],
        [0.9751],
        [0.5854],
        [0.6431],
        [0.8459],
        [0.8374],
        [0.4420],
        [0.2574],
        [0.1708],
        [0.4292],
        [0.1682]])
tensor([[0.9594, 0.3548, 0.9751, 0.5854, 0.6431, 0.8459, 0.8374, 0.4420, 0.2574,
         0.1708, 0.4292, 0.1682]])
tensor([[0.9594, 0.3548, 0.9751],
        [0.5854, 0.6431, 0.8459],
        [0.8374, 0.4420, 0.2574],
        [0.1708, 0.4292, 0.1682]])


In [ ]:
# GPU
print(torch.cuda.is_available())
# if torch.cuda.is_available():
#   device = torch.device("cuda")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.rand(3,2).to(device)
print(x)
x = x.to("cpu")
print(x)

True
tensor([[0.1159, 0.0656],
        [0.9751, 0.0762],
        [0.6860, 0.5650]], device='cuda:0')
tensor([[0.1159, 0.0656],
        [0.9751, 0.0762],
        [0.6860, 0.5650]])
